apiVersion: v1
kind: Service
metadata:
  name: emqxservice
  labels:
    svclbl: my-svc
spec:
  type: NodePort
  ports:
    - name: port1
      nodePort: 31000
      port: 1883
      targetPort: 1883
    - name: port2
      nodePort: 31001
      port: 8083
      targetPort: 8083
    - name: port3
      nodePort: 31002
      port: 18083
      targetPort: 18083
  selector:
    type: emqx

